### ISSUE TITLE
Twitter Handle

### ISSUE THREAD

**Issue by vermont42** [kyledold/WordOfTheDay#22]
I blog about iOS development at [racecondition.software](https://racecondition.software). I'm writing a post about SwiftUI-specific coding style using my findings from the open-source apps isowords, Wiggles, Pulse, Caffe, and (you guessed it) Word of the Day: English. I intend to thank the developers of the apps via Twitter when the post goes live. It doesn't look like you are on Twitter, but, if you are and would like the app to be mentioned, please provide your Twitter handle.

FWIW, my open-source SwiftUI app is [Conjuguer](https://github.com/vermont42/Conjuguer). I've already gotten some inspiration for how to improve its SwiftUI-specific coding style.

Cheerio.

**Comment by kyledold** [comment]
Hi Josh,

Thanks for reaching out.
I am actually am on Twitter :) @kyledold is my username.

Looking forward to reading the blog post.

Regards,
Kyle

**Comment by vermont42** [comment]
Cool, thanks.
